### ISSUE TITLE
Dandyland node rendering, not capturing into preview/save

### ISSUE THREAD

**Issue by Gabrielmtn** [sofakid/dandy#4]
If a Dandyland node is rendering within the node itself, but not sending to preview, is there a common error that comes to mind?

**Comment by Gabrielmtn** [comment]
For example, I want thinking about submitting a PR to add this to the example workflows, but I'm missing a rendering step, perhaps   
[Dandy Fluid .json](https://github.com/user-attachments/files/15741863/Dandy.Fluid.json)

**Comment by sofakid** [comment]
looks cool, and you're highlighting the need for a better "freeze" button.

When the render is done, you need to call dandy.continue() from the js code somewhere. otherwise it will wait around assuming you're not done rendering. 

If the scene is frozen, this just means it won't reload the iframe anymore, leaving it as is, and skipping the dandy.continue() requirement.. when it's animated however, it's not going to freeze the animation :/

like when you hit queue prompt, the scene will reload even if you've got it how you like it, but won't if frozen.. the freeze should really just capture everything when you hit freeze..

but to answer your question directly: you need to call dandy.continue() when you have it rendered how you want it.

**Comment by sofakid** [comment]
I'm also noticing it's not detecting that anything has changed and so isn't actually including it.. seems to render as a black square and then nothing has changed so it's ignored.

something something webgl not rendering to canvas the way i expected

**Comment by Gabrielmtn** [comment]
Ok I see, it sounds like it's only going to render the very first image when the sim is rendered, which is of course empty, an idea that come to mind:

- perhaps moving the fluid sim back in the node chain would be best, and simply sending a screenshot of the rendered frame after converting to latent would be better.
-

**Comment by sofakid** [comment]
I dunno even with freeze its sending a black canvas. 

I think you need a way to say we're done rendering, maybe a spacebar key handler or something. In this handler, stop animating, maybe a gl.flush() is needed, and definitely a dandy.continue().

**Comment by Gabrielmtn** [comment]
I'll try to debug a few different ways. I bet if I add a frame counter to the top right, it'll always show zero, that it's only ever rendering the very first frame. 

I'll try to work out getting it fixed in a discord where ComfyUI devs hang out, and if there's no solution, maybe I'll try to work on getting a live-view option set up for the DandyLand node, and submit a PR.

**Comment by Gabrielmtn** [comment]
I'm thinking right now that some sort of canvas.toDataURL on a blur event of the canvas could capture the canvas state I want, but I'll have to test it and figure out how to output it as well.

**Comment by sofakid** [comment]
Sorry, what do you mean by live-view? 

Even with freeze it shows a black output for me, it should capture the canvas content when its queued. I capture with canvas.toDataUrl(), and it's returning a blank image, I think a gl.flush() might be necessary, but I'm not super familiar with webgl.

I'd suggest aborting the animation after a half a sec, do a gl.flush(), and then dandy.continue()

**Comment by Gabrielmtn** [comment]
I'll explore that idea. 

Sorry for not being more clear, I just meant an easy solution would be something like the screenshare node from Mixlabs, and just screencap it, but I'd prefer to figure it out inside Dandy and submit a PR for an example workflow without requiring any other nodes.

As seen here: https://www.reddit.com/r/comfyui/comments/1884p01/this_plugin_enables_screen_sharing_and_realtime/
https://github.com/shadowcz007/comfyui-mixlab-nodes

**Comment by sofakid** [comment]
I see I see. Yeah this is a nice little example that shouldn't require extra steps, just gotta sort out when you want to stop animating and make sure the canvas is updated before continuing

**Comment by Gabrielmtn** [comment]
I think triggering the canvas.toDataUrl() when the canvas loses focus will work, I just don't know enough about how to then pipe it into the image output, will keep on trying :) Fun project!

**Comment by sofakid** [comment]
The way you pipe it to the image output is by leaving it in the canvas, and making sure it's flushed. calling dandy.continue() will trigger the waiting node to make a capture, it uses canvas.toDataUrl() and then sends it off to python.

when you queue the prompt it's going to reload the iframe, and so if you've drawn with the mouse it will forget that. if you freeze it, it won't reload, and you also won't need to call dandy.continue. when the node is executed in your graph, if it's frozen, will just capture whatever's there in the canvas. 

if it's not frozen it will wait at that node, and you could draw, and for instance when they stop dragging the mouse around, it could call gl.flush, dandy.continue, and the data would be sent then

**Comment by Gabrielmtn** [comment]
Brilliant, I should be able to wrap this up tonight.

**Comment by sofakid** [comment]
Also you probably don't need that CSS node

**Comment by Gabrielmtn** [comment]
After tweaking some more with glflush and continue, I think I'm going to have to try a different pattern for this in the JS. It always seems to want to only capture the first frame. I got it working with a hack using the "Image Grab PIL" node, since your nodes were working as a canvas playground, just not passing. 
![Screenshot 2024-06-08 202538](https://github.com/sofakid/dandy/assets/1121921/15e59bfd-7ffe-407d-9f34-ec394fe40fb5)

**Comment by sofakid** [comment]
It's cool that you've solved your problem but you've uncovered some worms in dandy that i need to sort out.

- freeze button should take a snapshot immediately and use that. people want to use the dandyland as a playground, and making them run some code after they have it nice is overcomplicating things
- it shouldn't be sending anything if dandy.continue isn't called, it should just sit there doing nothing

i'm going to make that freeze button do the right things, and get that original workflow to work with that

**Comment by Gabrielmtn** [comment]
My different approaches yielded a few interesting ideas people might have a good straightforward experience interacting with dandy, if at some point you want to dig into where my head was at with it. Happy to chat or continue the conversation here.

https://github.com/sofakid/dandy/assets/1121921/fe8f6eee-c896-43a8-a9f3-113459b8b26e



Here's a video of it working with the hack workaround

**Comment by Gabrielmtn** [comment]
Closed for now, can help organize into specific issues to be discussed if that'd be helpful.
