### ISSUE TITLE
How does accessing the DOM/Window object work in Dandy?

### ISSUE THREAD

**Issue by Gabrielmtn** [sofakid/dandy#5]
Hey this is an issue about lexical scope in Dandy.  

I couldn't seem to figure it out, but I'm sure you've thought about it, maybe you know.

Is it possible to use dandy to access the window scope?

Can one, for example, use Dandy to element.click() an element in the ComfyUI DOM?

**Comment by sofakid** [comment]
It's running in an iframe, you don't have direct access to the DOM of the parent window. However, you can send messages, if you made custom node that extends DandyTown, for instance, you can handle the message in ComfyUI's space. 

However most of comfyui is LiteGraph nodes rendered to a canvas, most of them aren't actually DOM elements. Some things are, and you could access them for sure.

Take a look at the DandyGradient for an example of the message handling.

dandy/web/examples/gradient_node.js is running in comfyland, you can access the window object here

dandy/web/examples/gradient.js is running in dandyland
